AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Resources:
    EC2-Instance1:
        Type: AWS::EC2::Instance
        Properties:
          DisableApiTermination: true
          ImageId: ami-067d1e60475437da2
          InstanceType: t2.micro
          KeyName: vockey
          SubnetId: subnet-0f5e6641e2eea4cf0
    SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Lab-security-group-description
            GroupName: Lab-security-group
            SecurityGroupIngress: 
                  - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0
            VpcId: vpc-038c0ecd4395cb38a